# From: https://github.com/JuliaStats/Clustering.jl

# Packages
using Clustering
using Distances
using Gadfly
using RDatasets

# CHOOSE DATA ---------------------------------------------------------------------------------------------------------
RDatasets.datasets("cluster")
xclara = dataset("cluster", "xclara");
names!(xclara, [symbol(i) for i in ["x", "y"]]);

# Visually identify three clusters.
plot(x = xclara[:x], y = xclara[:y], Geom.point())

# DATA PREPARATION ----------------------------------------------------------------------------------------------------
# Convert to an Array
xclara = convert(Array, xclara);

# Transpose (Each sample should be in a separate column for generating distance matrix).
xclara = xclara';

# DISTANCE MATRIX -----------------------------------------------------------------------------------------------------
dclara = pairwise(SqEuclidean(), xclara);   # The squared Euclidean distance
dclara[1:5, 1:5]

# K-MEANS -------------------------------------------------------------------------------------------------------------
# Perform k-means clustering using initial seeds. You can either specity the method or a vector of seeds generated by
# one of the initialisation methods above.
# Options for display are :none, :iter and :final.
xclara_kmeans = kmeans(xclara, 3, display = :iter)
@assert nclusters(xclara_kmeans) == 3

# Plot points coloured with cluster assignment.
plot(x = xclara[1,:], y = xclara[2,:], color = assignments(xclara_kmeans), Geom.point(),
     Scale.color_discrete_manual("blue", "red", "green"))
